apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
    role: {{ .Values.role }}
spec:
  containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.image }}
      ports:
        - containerPort: {{ .Values.container.port }}